[package]
name = "massa_cipher"
version = "29.1.0"
edition = "2021"

[dependencies]
displaydoc = { workspace = true }
thiserror = { workspace = true }
aes-gcm = { workspace = true }
pbkdf2 = { workspace = true }
rand = { workspace = true }
