[package]
name = "massa_cipher"
version = "0.26.0"
edition = "2021"

[dependencies]
displaydoc = {workspace = true}
thiserror = {workspace = true}
aes-gcm = {workspace = true}
pbkdf2 = {workspace = true}
rand = {workspace = true}
massa_serialization = {workspace = true}