# Generate git hooks run: cargo install rusty-hook && rusty-hook init
[hooks]
pre-commit= "cargo check && cargo fmt -- --check && cargo clippy -- -A clippy::uninlined-format-args"

[logging]
verbose = true
