[package]
name = "massa_hash"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3"
bs58 = { version = "0.4", features = ["check"] }
displaydoc = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nom = "7.1"

# custom modules
massa_serialization = { path = "../massa-serialization" }

[dev-dependencies]
serde_json = "1.0"
serial_test = "1.0"
