[package]
name = "massa_hash"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin_hashes = "0.10"
bs58 = { version = "0.4", features = ["check"] }
displaydoc = "0.2"
secp256k1 = { version = "0.20", features = ["rand-std"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nom = "7.1"

[dev-dependencies]
serde_json = "1.0"
serial_test = "0.5"
