[package]
name = "massa_versioning"
version = "0.26.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = []

[dependencies]
machine = {workspace = true}
parking_lot = {workspace = true}
thiserror = {workspace = true}
num = {workspace = true}
num_enum = {workspace = true}
nom = {workspace = true}
tracing = {workspace = true}
massa_time = {workspace = true}
massa_models = {workspace = true}
massa_serialization = {workspace = true}
massa_hash = {workspace = true}
massa_signature = {workspace = true}
massa-proto-rs = {workspace = true, "features" = ["tonic"]}
massa_db_exports = {workspace = true}

[dev-dependencies]
more-asserts = {workspace = true}
tempfile = {workspace = true}
massa_db_worker = {workspace = true}
