[package]
name = "massa_versioning"
version = "0.23.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
# This is from: https://github.com/rust-bakery/machine/pull/22
machine = { git = "https://github.com/antifuchs/machine", branch = "fix-workspace-build" }
parking_lot = "0.12"
thiserror = "1.0"
num_enum = "0.5"
nom = "=7.1"
tracing = "0.1"

# custom module
massa_time = { path = "../massa-time" }
massa_models = { path = "../massa-models" }
massa_serialization = { path = "../massa-serialization" }
massa_hash = { path = "../massa-hash" }
massa_signature = { path = "../massa-signature" }
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", branch = "main", features = ["tonic"] }
massa_db = { path = "../massa-db" }

[dev-dependencies]
more-asserts = "0.3"
tempfile = "3.5"
massa_db_worker = { path = "../massa-db-worker" }

[features]
testing = []
