[package]
name = "massa_graph"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
num = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
# custom modules
massa_pos_exports = { path = "../massa-pos-exports" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_signature = { path = "../massa-signature" }
massa_serialization = { path = "../massa-serialization"}

[dev-dependencies]
serial_test = "0.8"

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "massa_models/instrument",
]
