[package]
name = "massa-sdk-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "massa_sdk_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
massa_models = { path = "../massa-models" }
massa_serialization = { path = "../massa-serialization" }
