[package]
name = "massa_factory_exports"
version = "0.25.2"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[features]
testing = ["massa_models/testing", "massa_protocol_exports/testing", "massa_pool_exports/testing"]
sandbox = []

[dependencies]
displaydoc = {workspace = true}
thiserror = {workspace = true}
massa_hash = {workspace = true}
massa_models = {workspace = true}
massa_time = {workspace = true}
massa_signature = {workspace = true}
massa_pos_exports = {workspace = true}
massa_consensus_exports = {workspace = true}
massa_pool_exports = {workspace = true}
massa_protocol_exports = {workspace = true}
massa_storage = {workspace = true}
