[package]
name = "massa_network_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = { version = "2.4", features = ["serde"] }
futures = "0.3"
itertools = "0.10"
num_enum = "0.5"
nom = "7.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["full"] }
tracing = "0.1"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_network_exports = { path = "../massa-network-exports" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_versioning = { path = "../massa-versioning" }

[dev-dependencies]
serial_test = "1.0"
tempfile = "3.3"
massa_models = { path = "../massa-models", features = ["testing"] }
massa_network_exports = { path = "../massa-network-exports", features = [
    "testing",
] }

